language: php
php:
  - "5.6"
services:
  - mysql
before_script:
  - cd backend-service
  - cp .env.travis .env
  - mysql -e 'create database jobimarklet_tests;'
  - mysql -e "GRANT ALL PRIVILEGES ON jobimarklet_tests.* TO 'travis'@'%'"
  - composer self-update
  - composer install --no-interaction
script:
  - vendor/bin/phpunit
branches:
  Only:
    - master
    - develop
    - /(feature|release|hotfix)\/.*$/
    - /v?\d+\.\d+\.\d+
