language: php
php:
  - "5.6"
services:
  - mysql
before_script:
  - cd backend-service
  - cp .env.travis .env
  - mysql -e 'create database jobimarklet_tests;'
  - composer self-update
  - composer install --no-interaction
script:
  - cd backend-service
  - composer test
